pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build \
         --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA \
         --label build-number=$DRONE_BUILD_NUMBER \
         --label build-date="$(date)" \
         -t amouat/example-webserver:$DRONE_COMMIT_SHA .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run amouat/example-webserver:$DRONE_COMMIT_SHA /test.sh

  push:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASS=${HUB_PASS}
    commands:
      - docker login -u amouat -p $PASS
      - docker push amouat/example-webserver:$DRONE_COMMIT_SHA

  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull amouat/example-webserver:$DRONE_COMMIT_SHA
      - docker tag amouat/example-webserver:$DRONE_COMMIT_SHA amouat/example-webserver:production
      - docker stack deploy -c ./docker-compose.yml example-webserver
